version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    depends_on:
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  api:
    build:
        context: .
        dockerfile: ./Docker/DockerfileNode
  api2:
    build:
        context: .
        dockerfile: ./Docker/DockerfileNode2
    # ここを設定しなくても、localhost:80にリクエストを送ればいい
    # ports:
    #     - "8080:8080"
    # expose:
    #   - "8080"
