version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    depends_on:
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx/
      - ./nginx/files:/www/dir
    ports:
      - "80:80"
  api:
    build:
      context: .
      dockerfile: ./Docker/Node.Dockerfile
  api2:
    build:
      context: .
      dockerfile: ./Docker/Node2.Dockerfile
    # ここを設定しなくても、localhost:80にリクエストを送ればいい
    # ports:
    #     - "8080:8080"
    # expose:
    #   - "8080"
