version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    # これ必要なんだっけ？
    depends_on:
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx/
      - ./nginx/files:/www/dir
      # basic認証のuser, passwordの設定
      - ./nginx/htpasswd:/etc/nginx/htpasswd
    ports:
      - "80:80"


  api:
    build:
      context: .
      dockerfile: ./Docker/Node.Dockerfile
  api2:
    build:
      context: .
      dockerfile: ./Docker/Node2.Dockerfile
    # portを設定しなくても、localhost:80にリクエストを送ればいい
    # ports:
    #     - "8080:8080"
    # expose:
    #   - "8080"


  # loadbalancingするためのコンテナ
  api-load-balance1:
    build:
      context: .
      dockerfile: ./Docker/Node.Dockerfile
    environment:
      - PORT=8081
  api-load-balance2:
    build:
      context: .
      dockerfile: ./Docker/Node.Dockerfile
    environment:
      - PORT=8082
  api-load-balance3:
    build:
      context: .
      dockerfile: ./Docker/Node.Dockerfile
    environment:
      - PORT=8083
